[[constraint]]
  branch = "master"
  name = "bazil.org/fuse"

[[constraint]]
  branch = "master"
  name = "github.com/putdotio/go-putio"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"
